language: python
addons:
  postgresql: 11
  apt:
    packages:
    - postgresql-11-postgis-2.5
env:
  global:
    - STRATUMPASSWORD=BeMyDataBaePostGis!
before_script:
  - chmod +x sample_users.sh
  - chmod +x sample_schema.sh
script:
  - "./sample_users.sh"
  - "(export PGPASSWORD=$STRATUMPASSWORD && ./sample_schema.sh)"
  - "./src/test/run_all_tests.sh"
