language: python
services:
  - postgresql
addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12-postgis-3.0
env:
  global:
    - STRATUMPASSWORD=BeMyDataBaePostGis!
before_script:
  - chmod +x sample_users.sh
  - chmod +x sample_schema.sh
  - chmod +x src/test/run_all_tests.sh
  - psql -U postgres -c "create database gis"
script:
  - "(export PGDATABASE=gis && ./sample_users.sh)"
  - "(export PGPASSWORD=$STRATUMPASSWORD && export PGDATABASE=gis && ./sample_schema.sh)"
  - "./src/test/run_all_tests.sh"
