language: python
services:
  - postgresql
env:
  global:
    - STRATUMPASSWORD=BeMyDataBaePostGis!
before_script:
  - chmod +x sample_users.sh
  - chmod +x sample_schema.sh
  - chmod +x src/test/run_all_tests.sh
script:
  - "./sample_users.sh"
  - "(export PGPASSWORD=$STRATUMPASSWORD && ./sample_schema.sh)"
  - "./src/test/run_all_tests.sh"
